controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

user_register:
    path: /api/register
    controller: App\Controller\AuthenticationController\RegistrationController::index
    methods: POST

user_login:
    path: /api/login
    controller: App\Controller\AuthenticationController\LoginController::index
    methods: POST

user_logout:
    path: /api/logout
    methods: GET
