controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

user_register:
    path: /api/register
    controller: App\Controller\AuthenticationController\RegistrationController::index
    methods: POST

user_login:
    path: /api/login
    controller: App\Controller\AuthenticationController\LoginController::index
    methods: POST

user_logout:
    path: /api/logout
    methods: GET

add_rooms:
    path: /rooms/
    controller: App\Controller\RoomController::addRoom
    methods: POST

get_rooms:
    path: /rooms/
    controller: App\Controller\RoomController::getAllRooms

get_room_by_id:
    path: /rooms/room/{id}
    controller: App\Controller\RoomController::getRoomById

get_room_by_type:
    path: /rooms/room/
    controller: App\Controller\RoomController::getRoomByType
